In [5]:
# Data

company_detail_list = [
      {
          'name': 'Company 1',
          'domain': 'Retail',
          'country': 'United States'
      },
      {
          'name': 'Company 2',
          'domain': 'Technology',
          'country': 'United Kingdom'
      },
      {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'country': 'United States'
      }
  ]

employee_detail_list = [
     {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0005',
          'first_name': 'Ying Han',
          'last_name': 'Tan',
          'full_name': 'Ying Han Tan',
          'company': 'Company 1',
          'nationality': 'Australia'
      },
      {
          'name': 'EMP-0015',
          'first_name': 'Kenneth',
          'last_name': 'Ng',
          'full_name': 'Kenneth Ng',
          'company': 'Company 3',
          'nationality': 'United States'
      },
      {
          'name': 'EMP-0018',
          'first_name': 'Rubby',
          'last_name': 'Lee',
          'full_name': 'Rubby Lee',
          'company': 'Company 2',
          'nationality': 'Hong Kong'
      },
     {
          'name': 'EMP-0017',
          'first_name': 'Robert',
          'last_name': 'White',
          'full_name': 'Robert White',
          'company': 'Company 1',
          'nationality': 'United Kingdom'
      }
  ]

In [7]:
# Task 1: Dapatkan daftar semua Perusahaan dan urutkan berdasarkan Nama Perusahaan dalam urutan terbalik.
def sort_companies_by_name(company_detail_list):
    sorted_companies = sorted(company_detail_list, key=lambda x: x['name'], reverse=True)
    return [{'name': company['name']} for company in sorted_companies]

In [8]:
# Task 2: Cetak semua nilai Domain di setiap perusahaan
def print_company_domains(company_detail_list):
    for company in company_detail_list:
        print(f"{company['name']}: {company['domain']} ({company['country']})")

In [10]:
# Task 3: Daftar semua Karyawan yang bekerja berdasarkan domain perusahaan
def employees_by_domain(employee_detail_list, company_detail_list):
    domain_dict = {}
    for company in company_detail_list:
        domain_dict[company['domain']] = []
# Task 3: Daftar semua Karyawan yang bekerja berdasarkan domain perusahaan
def employees_by_domain(employee_detail_list, company_detail_list):
    domain_dict = {}
    for company in company_detail_list:
        domain_dict[company['domain']] = []
    
    for employee in employee_detail_list:
        for company in company_detail_list:
            if employee['company'] == company['name']:
                domain_dict[company['domain']].append(employee['full_name'])
                break
    return domain_dict

In [11]:
# Task 4: Karyawan beserta negara asal perusahaan
def employees_with_company_country(employee_detail_list, company_detail_list):
    result = []
    company_country_dict = {company['name']: company['country'] for company in company_detail_list}
    
    for employee in employee_detail_list:
        employee_info = {
            'full_name': employee['full_name'],
            'company': employee['company'],
            'country': company_country_dict[employee['company']]
        }
        result.append(employee_info)
    return result

In [12]:
# Task 5: Perusahaan beserta jumlah karyawan berdasarkan kebangsaan
def company_employee_nationality(employee_detail_list):
    nationality_count = {}
    for employee in employee_detail_list:
        company_name = employee['company']
        nationality = employee['nationality']
        
        if company_name not in nationality_count:
            nationality_count[company_name] = {}
        
        if nationality not in nationality_count[company_name]:
            nationality_count[company_name][nationality] = 0
        
        nationality_count[company_name][nationality] += 1
    
    result = [{'company': company, 'employee_nationality': nationalities} for company, nationalities in nationality_count.items()]
    return result

In [13]:
# Testing the functions with provided data
print("Task 1 Output:", sort_companies_by_name(company_detail_list))
print("\nTask 2 Output:")
print_company_domains(company_detail_list)
print("\nTask 3 Output:", employees_by_domain(employee_detail_list, company_detail_list))
print("\nTask 4 Output:", employees_with_company_country(employee_detail_list, company_detail_list))
print("\nTask 5 Output:", company_employee_nationality(employee_detail_list))

Task 1 Output: [{'name': 'Company 3'}, {'name': 'Company 2'}, {'name': 'Company 1'}]

Task 2 Output:
Company 1: Retail (United States)
Company 2: Technology (United Kingdom)
Company 3: Healthcare (United States)

Task 3 Output: {'Retail': ['John Doe', 'Ying Han Tan', 'Robert White'], 'Technology': ['Tom Smith', 'Rubby Lee'], 'Healthcare': ['Andrew Sebastian', 'Kenneth Ng']}

Task 4 Output: [{'full_name': 'John Doe', 'company': 'Company 1', 'country': 'United States'}, {'full_name': 'Tom Smith', 'company': 'Company 2', 'country': 'United Kingdom'}, {'full_name': 'Andrew Sebastian', 'company': 'Company 3', 'country': 'United States'}, {'full_name': 'Ying Han Tan', 'company': 'Company 1', 'country': 'United States'}, {'full_name': 'Kenneth Ng', 'company': 'Company 3', 'country': 'United States'}, {'full_name': 'Rubby Lee', 'company': 'Company 2', 'country': 'United Kingdom'}, {'full_name': 'Robert White', 'company': 'Company 1', 'country': 'United States'}]

Task 5 Output: [{'company': 'Company 1', 'employee_nationality': {'Australia': 2, 'United Kingdom': 1}}, {'company': 'Company 2', 'employee_nationality': {'United States': 1, 'Hong Kong': 1}}, {'company': 'Company 3', 'employee_nationality': {'United States': 2}}]